config/routes.rb
Rails.application.routes.draw do
  
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:new, :create]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'guest_login', to: 'sessions#new_guest'
  delete 'logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :technologies do
    resources :comments
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id            :bigint           not null, primary key
#  content       :text(65535)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  technology_id :bigint
#  user_id       :bigint
#
# Indexes
#
#  index_comments_on_technology_id  (technology_id)
#  index_comments_on_user_id        (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (technology_id => technologies.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :technology
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/technology.rb
# == Schema Information
#
# Table name: technologies
#
#  id         :bigint           not null, primary key
#  content    :text(65535)
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_technologies_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Technology < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  # 画像投稿
  has_one_attached :image

  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { maximum: 4294967296 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string(255)
#  name            :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :technologies, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user_logged_in, only: [:edit]
  before_action :set_technology, only: %i[create edit update destroy]
  before_action :correct_user, only: %i[edit destroy]
  before_action :correct_user_is_guest?, only: %i[create update]

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:success] = '正常に投稿されました'
      redirect_to technology_path(@technology)
    else
      @comments = @technology.comments.includes([:user])
      flash.now[:danger] = '投稿されませんでした'
      render 'technologies/show'
    end
  end

  def edit
  end

  def update
    @comment = @technology.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to technology_path(@technology)
      flash[:success] = '正常に更新されました'
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to technology_path(@technology)
    flash[:success] = '正常に削除されました'
  end

  private

  def set_technology
    @technology = Technology.find(params[:technology_id])
  end

  def comment_params
    params.require(:comment).permit(:content, :technology_id).merge(user_id: current_user.id)
  end

  def correct_user
    @comment = current_user.comments.find_by(id: params[:id])
    unless @comment
      redirect_to technology_path(@technology)
    end
  end
  
  def correct_user_is_guest?
    if current_user.email == 'guest@email.jp' 
      flash[:danger] = 'ゲストユーザーなので投稿できません。'
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      redirect_to root_path
    end
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  def new_guest
    user = User.find_by(email: 'guest@email.jp')
    if user
      session[:user_id] = user.id
      flash[:success] = 'ゲストユーザーとしてログインしました。'
      redirect_to root_path
    else
      flash[:success] = 'ゲストユーザーとしてログイン失敗しました。'
      redirect_to root_path
    end
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user&.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      true
    else
      # ログイン失敗
      false
    end
  end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :require_user_logged_in, only: %i[index show new edit]
  before_action :set_technology, only: %i[show edit update destroy]
  before_action :correct_user, only: %i[edit destroy]
  before_action :correct_user_is_guest?, only: %i[create update]

  def index
    @technologies = Technology.includes([:user])
                              .includes([image_attachment: :blob])
                              .order(id: :desc)
                              .page(params[:page])
                              .per(5)
  end

  def show
    @comment = Comment.new
    @comments = @technology.comments.includes([:user])
  end

  def new
    @technology = Technology.new
  end

  def create
    @technology = Technology.new(technology_params)
    if @technology.save
      flash[:success] = '正常に投稿されました'
      redirect_to technologies_path
    else
      flash.now[:danger] = '投稿されませんでした'
      render :new
    end
  end

  def edit; end

  def update
    if @technology.update(technology_params)
      flash[:success] = '正常に更新されました'
      redirect_to technologies_path
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  def destroy
    @technology.destroy
    flash[:success] = '正常に削除されました'
    redirect_to technologies_path
  end

  private

  def set_technology
    @technology = Technology.find(params[:id])
  end

  def technology_params
    params.require(:technology).permit(:title, :content, :image).merge(user_id: current_user.id)
  end

  def correct_user
    if @technology.user != current_user
      redirect_back(fallback_location: root_path)
    end
  end
  
  def correct_user_is_guest?
    if current_user.email == 'guest@email.jp' 
      flash[:danger] = 'ゲストユーザーなので投稿できません。'
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user.email, @user.password)
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def login(email, password)
    @user = User.find_by(email: email)
    if @user&.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      true
    else
      # ログイン失敗
      false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/comments/edit.html.erb
<u><h2 class='text-center'>コメント編集ページ</h2></u>
<%= form_with model:[@technology, @comment], local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group">
    <div class="form-group">
      <label>コメント</label>
      <%= f.text_area :content, class: "form-control", rows: "6" %>
    </div>
  </div>
  <div class="text-center">
    <div class="form-group">
      <%= f.submit "送信", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<div>
  <%= link_to '投稿詳細ページに戻る', technology_path(@technology) %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_flash_technologies.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<% if false %>
<header class="mb-4 sticky-top">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</header>
<% end %>

<% if true %>
<header class="mb-4 sticky-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Construction Technologies</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto"></ul>
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item">
            <a class="nav-link" href="#"><span class=mr-2>ユーザー名:</span><%= current_user.name %></a>
          </li>
          <li class="nav-item">
            <%= link_to '投稿一覧', technologies_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to '新規投稿', new_technology_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', logout_path, class: 'nav-link', method: :delete %>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'アカウント作成', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/technologies/_form.html.erb
<%= form_with model: @technology, local: true do |f| %>
  
  <%= render 'layouts/error_messages', model: f.object %>
  
  <div class="form-group">
    <label>タイトル</label>
    <%= f.text_field :title, class: "form-control", autocomplete: 'off' %>
  </div>
  <div class="form-group">
    <label>画像</label>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>説明</label>
    <%= f.text_area :content, class: "form-control", rows: "6" %>
  </div>
  <div class="text-center">
    <%= f.submit "送信", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/technologies/edit.html.erb
<u><h2 class='text-center'>投稿編集ページ</h2></u>

<%= render 'form' %>

<%= link_to '投稿詳細ページに戻る', technology_path %>

app/views/technologies/index.html.erb
<u><h2 class='text-center'>投稿一覧ページ</h2></u>
<% @technologies.each do |tech| %>
<div class='mt-5'>
  <h3 class='h4'><%= link_to tech.title, technology_path(tech), class: 'text-muted' %></h3>
  <div class="row">
    <div class="col-md-3 index_image text-center">
      <% if tech.image.attached? %>
        <%= image_tag tech.image.variant(resize: "256x144") %>
      <% else %>
        <%= image_tag 'no_image.jpg', width: '256' %>
      <% end %>
    </div>
    <div class="col-md-9">
      <div class='tech_text'><%= tech.content %></div>
      <div class='remarks text-right mt-2'>
        <span class="mb-0"><span class=mr-2>投稿者名:</span><%= tech.user.name %></span>
        <span class='ml-4'><span class=mr-2>更新日時:</span><%= tech.updated_at.strftime("%Y-%m-%d %H:%M") %></span>
        <span class='ml-4'>
          [ <%= link_to '編集', edit_technology_path(tech) %> ]
          [ <%= link_to '削除', technology_path(tech), method: :delete, data:{ confirm: '本当に削除してもよろしいですか？' } %> ]
        </span>
      </div>
    </div>
  </div>
</div>
<% end %>
<%= paginate @technologies %>

app/views/technologies/new.html.erb
<u><h2 class='text-center'>新規投稿ページ</h2></u>

<%= render 'form' %>

app/views/technologies/show.html.erb
<u><h2 class='text-center'>投稿詳細ページ</h2></u>
<div class="row mt-5">
  <div class="col-md-12">
    <h4><%= @technology.title %></h4>
    <div class='text-center'>
      <% if @technology.image.attached? %>
        <%= image_tag @technology.image.variant(resize: "667x375"), class: 'show_image' %>
      <% end %>
    </div>
    <div class='show_text'>
      <%= simple_format(@technology.content) %>
    </div>
    <div class='remarks text-right mt-2'>
      <span class="mb-0 mr-10"><span class=mr-2>投稿者名:</span><%= @technology.user.name %></span>
      <span class='ml-4'><span class='mr-2'>更新日時:</span><%= @technology.updated_at.strftime("%Y-%m-%d %H:%M") %></span>
      <span class='ml-4'>
        [ <%= link_to '編集', edit_technology_path(@technology) %> ]
        [ <%= link_to '削除', technology_path(@technology), method: :delete, data:{ confirm: '本当に削除してもよろしいですか？' } %> ]
      </span>
    </div>
    <hr size="5" noshade>
    
    <div>
      <h3>コメント一覧</h3>
        <% if @comments.any? %>
          <% @comments.each do |com| %>
            <p class='mb-0'><%= com.content %></p>
            <div class='remarks text-right mt-2'>
              <span class="mb-0"><span class=mr-2>投稿者名:</span><%= com.user.name %></span>
              <span class='ml-4'><span class='mr-2'>更新日時:</span><%= com.updated_at.strftime("%Y-%m-%d %H:%M") %></span>
              <span class='ml-4'>
                [ <%= link_to '編集', edit_technology_comment_path(@technology, com) %> ]
                [ <%= link_to '削除', technology_comment_path(@technology, com), method: :delete, data:{ confirm: '本当に削除してもよろしいですか？'} %> ]  
              </span>
            </div>
            <hr>
          <% end %>
        <% else %>
          <p>まだコメントはありません。</p>
        <% end %>
    </div>
    
    <h3>新しいコメントを投稿します。</h3>
    <%= form_with model: [@technology,@comment], local: true do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <%= f.hidden_field :technology_id, { value: @technology.id} %>
      <div class="form-group">
        <label>コメント</label>
        <%= f.text_area :content, class: 'form-control', rows: "6" %>
      </div>
      <div class="text-center mb-3">
        <%= f.submit "送信", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/toppages/index.html.erb
<div class="center toppage_image">
  <div class="text-center">
    <div class="introduction">
      <p class="h2 pt-5">建設技術投稿サイトへようこそ</p>
      <p class="h4 mb-0">このサイトは建設関係の技術情報を投稿するサイトです。</p>
      <p class="h4">お気軽に投稿してみてください！</p>
    </div>
    <% if logged_in? %>
      <%= link_to '投稿一覧ページへ', technologies_path, class: 'button mb-2', :style => 'color: white;' %>
      <%= link_to '新規投稿ページへ', new_technology_path, class: 'button', :style => 'color: white;' %>
    <% else %>
      <%= link_to 'ログイン', login_path, class: 'button mb-2', :style => 'color: white;' %>
      <%= link_to 'アカウント作成', signup_path, class: 'button', :style => 'color: white;' %>
    <% end %>
    <p class="introduction h5 mt-2"><%= link_to '日刊建設工業新聞', 'https://www.decn.co.jp/', :style => 'color: white;' %>から一部引用しております。</p>
  </div>
</div>

app/views/users/new.html.erb
<u><h2 class='text-center'>アカウント作成</h2></u>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control', autocomplete: 'off' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control', autocomplete: 'off' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（確認）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'アカウントを作成する', class: 'btn btn-primary btn-block' %>
    <% end %>
    <p><%= link_to 'ログインはこちら', login_path %></p>
  </div>
</div>